### ISSUE TITLE
Type errors on latest

### ISSUE THREAD

**Issue by roobscoob** [fails-components/webtransport#250]
![img](https://s3.hall.ly/rol/2024/02/FeIPH1NHhG.png)

an `index.d.ts` file is looked for, but only `index.browser.d.ts` and `index.node.d.ts` exist.

**Comment by martenrichter** [comment]
Ok, I thought we have fixed this here:
https://github.com/fails-components/webtransport/issues/233

I am sorry, but I am not using typescript, so I often encounter these problems.

Of course, I would like to fix this. Anyone an idea, who has a knowledge of types?
This is an open problem...
https://github.com/microsoft/TypeScript/issues/29128

I could make the node version default?

**Comment by endel** [comment]
Hi @martenrichter 👋 I think it is safe to use the "node" version for the types as default. I don't think this package would be used to target web browsers

**Comment by martenrichter** [comment]
Well, it could be if the polyfill/ponyfill feature is used for web transport over websocket.
I was thinking, if I create a joint index file just for types, where I include both...

**Comment by AugusDogus** [comment]
This unfortunately is still an issue on v1.1.4

![Image](https://github.com/user-attachments/assets/922285f2-c3fc-494d-a261-1c0928f8f810)

**Comment by martenrichter** [comment]
Maybe I would not see it because I do not use typescript. I am open to PRs related to the ts issue.
@achingbrain : Can you have a look as you introduced the original type setup (of course originally  without the node /browser split)?
